POST http://localhost:5001/jmt/user/new
Content-Type: application/json

{
    "text" : "Tanmddday patil"
}

###get users
GET  http://localhost:5000/jmt/users

###
POST http://localhost:5001/login/new
Content-Type: application/json

{
    "text" : "RIL"
}
###
DELETE  http://localhost:5001/test
###
DELETE http://localhost:5001/user/delete-all
### Delete user
DELETE http://localhost:5001/user/delete/64492fd752226536db347251

###get logins
GET  http://localhost:5001/logins
